"""initial postgres migration

Revision ID: e0bfb8ff04f0
Revises: 001_rename_api_keys_to_cats
Create Date: 2026-02-26 14:50:08.726733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bfb8ff04f0'
down_revision: Union[str, Sequence[str], None] = '001_rename_api_keys_to_cats'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_collection_id'), table_name='cats')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='cats')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='cats')
    op.create_index(op.f('ix_cats_collection_id'), 'cats', ['collection_id'], unique=False)
    op.create_index(op.f('ix_cats_key_hash'), 'cats', ['key_hash'], unique=True)
    op.create_index(op.f('ix_cats_user_id'), 'cats', ['user_id'], unique=False)
    op.alter_column('documents', 'collection_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'collection_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_cats_user_id'), table_name='cats')
    op.drop_index(op.f('ix_cats_key_hash'), table_name='cats')
    op.drop_index(op.f('ix_cats_collection_id'), table_name='cats')
    op.create_index(op.f('ix_api_keys_user_id'), 'cats', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'cats', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_collection_id'), 'cats', ['collection_id'], unique=False)
    # ### end Alembic commands ###
