from nicegui import APIRouter, ui

from web_ui.auth import load_tokens_from_storage, require_auth
from web_ui.components import render_page
from web_ui.utils import handle_api_error

router = APIRouter(prefix="")

supported_types = ["markdown", "text", "html", "json", "yaml", "xml", "python", "javascript"]


@router.page("/editor/{doc_id}")
async def editor_page(doc_id: str):
    await load_tokens_from_storage()

    if not require_auth():
        return

    def content():
        from web_ui.auth import get_api_client

        api_client = get_api_client()

        response = api_client.get_document(doc_id)
        if not handle_api_error(response, "Failed to load document"):
            ui.navigate.to("/documents")
            return

        doc = response.json()

        current_doc = {
            "title": doc["title"],
            "document_type": doc["document_type"],
            "content": doc.get("content", ""),
        }

        with ui.row().classes("w-full items-center justify-between mb-4"):
            with ui.row().classes("items-center gap-2"):
                ui.button(icon="arrow_back", on_click=lambda: ui.navigate.to("/documents")).props(
                    "flat round"
                )
                ui.icon("edit", size="md")
                ui.input(value=current_doc["title"]).classes("text-xl font-bold w-64").bind_value(
                    current_doc, "title"
                )

            with ui.row().classes("items-center gap-2"):
                ui.select(
                    options=supported_types,
                    label="Document Type",
                ).classes("w-40").bind_value(current_doc, "document_type")
                ui.button(
                    icon="visibility",
                    on_click=lambda: ui.navigate.to(f"/viewer/{doc_id}"),
                ).props("flat round")

        ui.separator()

        # Make CodeMirror auto-resize to fit content (no internal scrollbar).
        #
        # Three layers of fixed-height styling must be defeated:
        #   1. nicegui.css:       .nicegui-codemirror { height: 16rem }
        #   2. codemirror.js:     .cm-editor { height: 100% }   (via EditorView.theme)
        #   3. codemirror.js:     .cm-scroller { overflow: auto } (via EditorView.theme)
        #
        # Layer 1 is overridden with an inline style on the wrapper element.
        # Layers 2 & 3 are generated by CM6 with scoped class selectors, so
        # plain CSS cannot reliably override them — we use run_javascript to
        # set inline styles on the CM DOM elements after mount.
        editor = ui.codemirror(current_doc["content"]).classes("w-full border min-h-[300px]")
        editor.style("height: auto")
        editor.theme = "dark"
        editor.line_wrapping = True
        editor.bind_value(current_doc, "content")

        editor_id = editor.id
        ui.timer(
            0.1,
            lambda: ui.run_javascript(f"""
                const wrapper = document.getElementById('c{editor_id}');
                if (wrapper) {{
                    const cmEditor = wrapper.querySelector('.cm-editor');
                    const cmScroller = wrapper.querySelector('.cm-scroller');
                    if (cmEditor) cmEditor.style.setProperty('height', 'auto', 'important');
                    if (cmScroller) cmScroller.style.setProperty('overflow-y', 'hidden', 'important');
                }}
            """),
            once=True,
        )

        with ui.row().classes("w-full justify-end gap-2 mt-4"):

            async def save():
                resp = api_client.update_document(
                    doc_id,
                    title=current_doc["title"],
                    document_type=current_doc["document_type"],
                    content=current_doc["content"],
                )
                if handle_api_error(resp, "Failed to update document"):
                    ui.notify("Document updated successfully")

            ui.button("Save Changes", on_click=save).props("color=primary")
            ui.button(
                "Cancel",
                on_click=lambda: ui.navigate.to(f"/viewer/{doc_id}"),
            ).props("flat")

    render_page(content)
